routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// roocket.ir/admin
Route::get('/' , 'HomeController@index');
Route::get('/search' , 'HomeController@search');

//Route::get('/articles' , 'ArticleController@index');
Route::get('/courses' , 'CourseController@index');
Route::get('/articles/{articleSlug}' , 'ArticleController@single');
Route::get('/courses/{courseSlug}' , 'CourseController@single');
Route::post('/comment' , 'HomeController@comment');
Route::get('/user/active/email/{token}' , 'UserController@activation')->name('activation.account');
Route::get('/sitemap' , 'SitemapController@index');
Route::get('/sitemap-articles' , 'SitemapController@articles');
Route::get('/feed/articles','FeedController@articles');

// Download Route
Route::get('/download/{episode}' , 'CourseController@download');


Route::get('telegram','TelegramController@telegram');
Route::post('/396603472:AAGLckyApu-oMnURzd59DgNXbsCqFhgPjHA/webhook' , 'TelegramController@webhook');

Route::group(['middleware' => 'auth'] , function () {
   $this->post('/course/payment' , 'CourseController@payment');
   $this->get('/course/payment/checker' , 'CourseController@checker');


   $this->group(['prefix' => '/user/panel'] , function(){
      $this->get('/' , 'UserController@index')->name('user.panel');
      $this->get('/history' , 'UserController@history')->name('user.panel.history');
      $this->get('/vip' , 'UserController@vip')->name('user.panel.vip');

       $this->post('/payment' , 'UserController@vipPayment')->name('user.panel.vip.payment');
       $this->get('/checker' , 'UserController@vipChecker')->name('user.panel.vip.checker');
   });
});


// namespace('Admin')->prefix('admin')
Route::group(['namespace' => 'Admin' , 'middleware' => ['auth' , 'checkAdmin'], 'prefix' => 'admin'],function (){
    $this->get('/panel' , 'PanelController@index');
    $this->post('/panel/upload-image' , 'PanelController@uploadImageSubject');
    $this->resource('articles' , 'ArticleController');
    $this->resource('courses' , 'CourseController');

    // Comment Section
    $this->get('comments/unsuccessful' , 'CommentController@unsuccessful');
    $this->resource('comments' , 'CommentController');

    // Payment Section
    $this->get('payments/unsuccessful' , 'PaymentController@unsuccessful');
    $this->resource('payments' , 'PaymentController');

    $this->resource('episodes' , 'EpisodeController');
    $this->resource('roles' , 'RoleController');
    $this->resource('permissions' , 'PermissionController');

    $this->group(['prefix' => 'users'],function (){
       $this->get('/' , 'UserController@index');
       $this->resource('level' , 'LevelManageController' , ['parameters' => ['level' => 'user']]);
       $this->delete('/{user}/destroy' , 'UserController@destroy')->name('users.destroy');
    });
});

Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->get('logout', 'LoginController@logout')->name('logout');

    // Login And Register With Google
    $this->get('login/google', 'LoginController@redirectToProvider');
    $this->get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'RegisterController@register');

    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});


Route::get('/home', 'HomeController@index')->name('home');

app/Payment.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $fillable = [
        'resnumber',
        'price',
        'course_id',
        'payment'
    ];
    public function scopeSpanningPayment($query , $month , $paymen) {
        $query->selectRaw('monthname(created_at) month , count(*) published')
            ->where('created_at' , '>' , Carbon::now()->subMonth($month))
            ->wherePayment($paymen)
            ->groupBy('month')
            ->latest();
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/Admin/PaymentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Payment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $payments = Payment::with('user')->wherePayment(1)->latest()->paginate(20);
        return view('Admin.payments.all' , compact('payments'));
    }

    public function unsuccessful()
    {
        $payments = Payment::with('user')->wherePayment(0)->latest()->paginate(20);
        return view('Admin.payments.unsuccessful' , compact('payments'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Payment $payment)
    {
        $payment->update([
            'payment' => 1
        ]);
        // Alert

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Payment $payment)
    {
        $payment->delete();
        // Alert

        return back();
    }
}

resources/views/Admin/payments/all.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>همه نظرات</h2>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>نام کاربر</th>
                    <th>مقدار پرداختی</th>
                    <th>نوع پرداخت</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($payments as $payment)
                    <tr>
                        <td>{{ $payment->user->name }}</td>
                        <td>{{ $payment->price }}</td>
                        @if($payment->course_id == 'vip')
                            <td>بابت عضویت ویژه</td>
                        @else
                            <td>{{ $payment->course->title }}</td>
                        @endif
                        <td>
                            <form action="{{ route('payments.destroy'  , ['id' => $payment->id]) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <div class="btn-group btn-group-xs">
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                </div>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            {!! $payments->render() !!}
        </div>
    </div>
@endsection

resources/views/Admin/payments/unsuccessful.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>همه نظرات</h2>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>نام کاربر</th>
                    <th>مقدار پرداختی</th>
                    <th>نوع پرداخت</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($payments as $payment)
                    <tr>
                        <td>{{ $payment->user->name }}</td>
                        <td>{{ $payment->price }}</td>
                        @if($payment->course_id == 'vip')
                            <td>بابت عضویت ویژه</td>
                        @else
                            <td>{{ $payment->course->title }}</td>
                        @endif
                        <td>
                            <div style="display: flex">
                                <form action="{{ route('payments.destroy'  , ['id' => $payment->id]) }}" method="post">
                                    {{ method_field('delete') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-xs btn-danger">حذف</button>
                                </form>
                                <form style="margin-right: 5px" action="{{ route('payments.update'  , ['id' => $payment->id]) }}" method="post">
                                    {{ method_field('patch') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-xs btn-success">تایید</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            {!! $payments->render() !!}
        </div>
    </div>
@endsection